name: checking-eslint-rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check-lint
        run: npm run lint:fix

      - name: build the docker image
        run: |
          docker build -t app .
          docker login -u malek02 -p dckr_pat_q3kToueYX4dTe0PvnztBVYOHEY8
          docker tag app malek02/test
          docker push malek02/test